download/urls.py
from django.contrib import admin
from django.urls import path,include
from download.views import Download,Index
app_name='download_video'

urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('download/',Download.as_view(),name='download')
]

download_tecent_video/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('download.urls',namespace='download_video'))
]

download/models.py
from django.db import models

# Create your models here.

download/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from download_video import Downloadvideo

# Create your views here.

class Index(View):
    def get(self, request):
        return render(request, 'index.html')


class Download(View):
    def post(self, request):
        key_name = request.POST.get('key_name')
        file_path = request.POST.get('file_path')
        try:
            download = Downloadvideo(key_name, file_path)
            results=download.run()
        except Exception as e:
            print(e)

        finally:
            results.append('下载完成')
            return HttpResponse(results)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>视频批量下载器</title>
</head>
<body>

<form method='post' action="{% url 'download_video:download' %}">
    {% csrf_token %}
    <input type="text" name="key_name" > <br>
    <input type="text" name="file_path" >
    <input type="submit" value="提交">
</form>
</body>
</html>